"""migra todas las tablas

Revision ID: b97582f59797
Revises: 
Create Date: 2025-10-12 22:03:01.064164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97582f59797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancion',
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('duracion', sa.Time(), nullable=True),
    sa.Column('tamano', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id_cancion')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_item', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('correo',
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('id_us', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_us'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('correo')
    )
    op.create_table('correo_proveedor',
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('correo')
    )
    op.create_table('discoMp3',
    sa.Column('id_discoMp3', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('duracion', sa.Time(), nullable=True),
    sa.Column('tamano', sa.Numeric(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('id_item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_item'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id_discoMp3')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_us', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('medio_pago', sa.String(length=50), nullable=True),
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['id_us'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('recopilacion',
    sa.Column('id_recopilacion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('id_us', sa.Integer(), nullable=True),
    sa.Column('publica', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_us'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_recopilacion')
    )
    op.create_table('telefono',
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('id_us', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_us'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('telefono')
    )
    op.create_table('telefono_proveedor',
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('telefono')
    )
    op.create_table('vinilo',
    sa.Column('id_vinilo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('artista', sa.String(length=100), nullable=True),
    sa.Column('anio_salida', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('id_cancion', sa.Integer(), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('id_item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id_vinilo')
    )
    op.create_table('discoMp3Cancion',
    sa.Column('id_discoMp3', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_discoMp3'], ['discoMp3.id_discoMp3'], ),
    sa.PrimaryKeyConstraint('id_discoMp3', 'id_cancion')
    )
    op.create_table('recopilacionCancion',
    sa.Column('id_recopilacion', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_recopilacion'], ['recopilacion.id_recopilacion'], ),
    sa.PrimaryKeyConstraint('id_recopilacion', 'id_cancion')
    )
    op.create_table('valoracion',
    sa.Column('id_val', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_us', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_us'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_val')
    )
    op.create_table('viniloCancion',
    sa.Column('id_vinilo', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_vinilo'], ['vinilo.id_vinilo'], ),
    sa.PrimaryKeyConstraint('id_vinilo', 'id_cancion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viniloCancion')
    op.drop_table('valoracion')
    op.drop_table('recopilacionCancion')
    op.drop_table('discoMp3Cancion')
    op.drop_table('vinilo')
    op.drop_table('telefono_proveedor')
    op.drop_table('telefono')
    op.drop_table('recopilacion')
    op.drop_table('pedido')
    op.drop_table('discoMp3')
    op.drop_table('correo_proveedor')
    op.drop_table('correo')
    op.drop_table('usuario')
    op.drop_table('proveedor')
    op.drop_table('item')
    op.drop_table('cancion')
    # ### end Alembic commands ###
